insert into Countries
    (code, name, sortOrder)
values
    ('World','World', 3),
('Africa','Africa', 3),
('AFRICOM','AFRICOM', 3),
('Americas','Americas', 3),
('Antarctic','Antarctic', 3),
('Antarctica','Antarctica', 3),
('Arabian Peninsula','Arabian Peninsula', 3),
('Arabian Sea','Arabian Sea', 3),
('Arctic','Arctic', 3),
('Arctic Ocean','Arctic Ocean', 3),
('Asia/Pacific','Asia/Pacific', 3),
('Atlantic Ocean','Atlantic Ocean', 3),
('Baltic Sea','Baltic Sea', 3),
('Black Sea','Black Sea', 3),
('Caribbean','Caribbean', 3),
('CENTCOM','CENTCOM', 3),
('East China Sea','East China Sea', 3),
('Eastern Africa','Eastern Africa', 3),
('EUCOM','EUCOM', 3),
('Europe/Eurasia','Europe/Eurasia', 3),
('Gulf of Guinea','Gulf of Guinea', 3),
('Gulf of Suez','Gulf of Suez', 3),
('Horn of Africa','Horn of Africa', 3),
('Indian Ocean','Indian Ocean', 3),
('Korea Bay','Korea Bay', 3),
('Latin America','Latin America', 3),
('Luzon Strait','Luzon Strait', 3),
('Mediterranean Sea','Mediterranean Sea', 3),
('Middle East','Middle East', 3),
('North America','North America', 3),
('NORTHCOM','NORTHCOM', 3),
('Oceania','Oceania', 3),
('Pacific Ocean','Pacific Ocean', 3),
('PACOM','PACOM', 3),
('Red Sea','Red Sea', 3),
('Sea of Japan','Sea of Japan', 3),
('SOCOM','SOCOM', 3),
('South America','South America', 3),
('South China Sea','South China Sea', 3),
('SOUTHCOM','SOUTHCOM', 3),
('STRATCOM','STRATCOM', 3),
('Suez Canal','Suez Canal', 3),
('Taiwan Strait','Taiwan Strait', 3),
('Yellow Sea','Yellow Sea', 3);
